/**
 * DO NOT MODIFY THIS CODE
 *
 * Place all of your changes in RecurringApplicationCharge.java
 *
 * It has been machine generated from fixtures and your changes will be
 * lost if anything new needs to be added to the API.
 **/
// Last Generated: 2011-09-26T15:53:49-04:00
package com.shopify.api.resources;

import com.shopify.api.resources.Image;
import com.shopify.api.resources.Option;
import com.shopify.api.resources.ShopifyResource;
import com.shopify.api.resources.Variant;
import org.codehaus.jackson.annotate.JsonProperty;

import java.util.List;

/**
 * This code has been machine generated by processing the single entry
 * fixtures found from the Shopify API Documentation
 */

public class MGRecurringApplicationCharge extends ShopifyResource {

	@JsonProperty("activated_on")
	public String getActivatedOn() {
		return (String)getAttribute("activated_on");
	}
	@JsonProperty("activated_on")
	public void setActivatedOn(String _activated_on) {
		setAttribute("activated_on", _activated_on);
	}

	@JsonProperty("billing_on")
	public String getBillingOn() {
		return (String)getAttribute("billing_on");
	}
	@JsonProperty("billing_on")
	public void setBillingOn(String _billing_on) {
		setAttribute("billing_on", _billing_on);
	}


	@JsonProperty("cancelled_on")
	public String getCancelledOn() {
		return (String)getAttribute("cancelled_on");
	}
	@JsonProperty("cancelled_on")
	public void setCancelledOn(String _cancelled_on) {
		setAttribute("cancelled_on", _cancelled_on);
	}

	@JsonProperty("confirmation_url")
	public String getConfirmationUrl() {
		return (String)getAttribute("confirmation_url");
	}
	@JsonProperty("confirmation_url")
	public void setConfirmationUrl(String _confirmation_url) {
		setAttribute("confirmation_url", _confirmation_url);
	}

    @JsonProperty("created_at")
    public String getCreatedAt() {
        return (String)getAttribute("created_at");
    }
    @JsonProperty("created_at")
    public void setCreatedAt(String _created_at) {
        setAttribute("created_at", _created_at);
    }

	/*@JsonProperty("id")
	public Long getId() {
		return (Long)getAttribute("id");
	}
	@JsonProperty("id")
	public void setId(Long _id) {
		setAttribute("id", _id);
	}*/

	@JsonProperty("name")
	public String getName() {
		return (String)getAttribute("name");
	}
	@JsonProperty("name")
	public void setName(String _name) {
		setAttribute("name", _name);
	}

	@JsonProperty("price")
	public Double getPrice() {
		return (Double)getAttribute("price");
	}
	@JsonProperty("price")
	public void setPrice(Double _price) {
		setAttribute("price", _price);
	}

	@JsonProperty("return_url")
	public String getReturnUrl() {
		return (String)getAttribute("return_url");
	}
	@JsonProperty("return_url")
	public void setReturnUrl(String _return_url) {
		setAttribute("return_url", _return_url);
	}

    @JsonProperty("status")
    public String getStatus() {
        return (String)getAttribute("status");
    }
    @JsonProperty("status")
    public void setStatus(String _status) {
        setAttribute("status", _status);
    }

    @JsonProperty("test")
    public Boolean getTest() {
        return (Boolean)getAttribute("test");
    }
    @JsonProperty("test")
    public void setTest(Boolean _test) {
        setAttribute("test", _test);
    }

    @JsonProperty("trial_days")
    public Integer getTrialDays() {
        return (Integer)getAttribute("trial_days");
    }
    @JsonProperty("trial_days")
    public void setTrialDays(Integer _trial_days) {
        setAttribute("trial_days", _trial_days);
    }


    @JsonProperty("trial_ends_on")
    public String getTrialEndsOn() {
        return (String)getAttribute("trial_ends_on");
    }
    @JsonProperty("trial_ends_on")
    public void setTrialEndsOn(String _trial_ends_on) {
        setAttribute("trial_ends_on", _trial_ends_on);
    }

    @JsonProperty("updated_at")
    public String getUpdatedAt() {
        return (String)getAttribute("updated_at");
    }
    @JsonProperty("updated_at")
    public void setUpdatedAt(String _updated_at) {
        setAttribute("updated_at", _updated_at);
    }
}
