package com.shopify.api.resources;

import com.shopify.api.resources.MGProduct;

/**
* This code has been machine generated by processing the single entry
* fixtures found from the Shopify API Documentation
*/
  
public class RecurringApplicationCharge extends MGRecurringApplicationCharge {

}